### ISSUE TITLE
Fresh LZA Deployment Fail

### ISSUE THREAD

**Issue by Tochey** [awslabs/landing-zone-accelerator-on-aws#243]
**Describe the bug**
The `AWSAccelerator-Pipeline` fails in the deploy phase for a brand new account. Seems like a codebuild service quota issue. I cant seem to find a note or documentation on this.

**To Reproduce**
Create a brand new management account, complete the prerequisites [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html) and deploy the [LZA](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/deployment-overview.html)

**Expected behavior**
`AWSAccelerator-Pipeline` should complete successfully

**Please complete the following information about the solution:**

- [v1.4.3] Version: [e.g. v1.1.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [us-east-1] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [n/a] If the answer to the previous question was yes, are the changes available on GitHub?
- [yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [no] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/54341970/7235edf5-8b18-438d-a056-aa2908ad1c32)

**Additional context**

**Comment by bo1984** [comment]
Hi @Tochey , thank you for using the Landing Zone Accelerator on AWS solution. As this is a service limit issue with AWS CodeBuild, by default your account will not allow multiple concurrent runs for AWS CodeBuild. You can submit a service limit request in the console or CLI. Here's a [link](https://docs.aws.amazon.com/servicequotas/latest/userguide/request-quota-increase.html) for reference. I will keep this issue open awaiting confirmation that this is resolved for you.

**Comment by joeshawfieldatayo** [comment]
The only options seem to apply to OS Type/Size. I am assuming the LZA is using Linux. I am also assuming this also only required for the Master? This seems like it will be a constant issue in the LZA and quite problematic

**Comment by jacekhewko** [comment]
Hey,

We are facing similar problem. What is interesting, we're not trying to launch concurrent runs - it is always one run at a time. So this error seem somewhat irrevelant.

We can try to exceed limits to see if this really helps, but which limit should we actually point?

Thanks,
Jacek

**Comment by joeshawfieldatayo** [comment]
The single Pipeline run itself has stages where the stage has multiple build components (side by side) that both run within a stage and I think that is the rub.  The final stage has 3. IN the last couple LZA we went ahead and requested the increase in concurrent build jobs just to be safe, along with some other quota increases (more than 10 accounts).

**Comment by TalOren** [comment]
Hey,

We are facing the same issue, the default for concurrent is set to 5 so I do not understand why it is still failing.

Thanks
Tal
