### ISSUE TITLE
UpdatePipelineGithubToken missing permissions

### ISSUE THREAD

**Issue by rinaudjaws** [awslabs/landing-zone-accelerator-on-aws#739]
**Describe the bug**
When [access token is expired](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-github-personal-access-token-expired.html) and a user updates the secret, UpdatePipelineGithubToken fails due to missing permissions "codestar-connections:PassConnection"

**To Reproduce**
Revoke Github access token, update secret in Secrets Manager, check UpdatePipelineGithubToken Lambda function.

**Expected behavior**

UpdatePipelineGithubToken should have updated CodePipeline and Codestar successfully.
 
**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.11.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [X] Region: [e.g. eu-north-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [X] Were there any errors in the CloudWatch Logs? Yes,
```
AccessDeniedException: User: arn:aws:sts::01234567890:assumed-role/AWSAccelerator-InstallerS-UpdatePipelineLambdaRole/AWSAccelerator-InstallerS-UpdatePipelineGithubToke-<ID> is not authorized to perform: codestar-connections:PassConnection on resource: arn:aws:codeconnections:eu-north-1:01234567890:connection/CONNECTION-UID because no identity-based policy allows the codestar-connections:PassConnection action
```

**Comment by Athanasii** [comment]
Hello @rinaudjaws , thank you for filing an issue with the Landing Zone Accelerator team! We are currently looking into the issue you've reported and will provide a status update as soon as possible.

**Comment by davidvr99** [comment]
I got it fixed by just updating to latest version 1.11.2

Tried to add permission directly on both roles for Manual or Lambda update but still same issue that its not authorized to perform: codeconnections:UseConnection

Once you use template (SO0199) Landing Zone Accelerator on AWS. Version 1.11.2 and change on your parameter to version 1.11.2 its now working (have to update my current Stack).

**Comment by richardkeit** [comment]
Thank you @davidvr99 for posting the fix.

@rinaudjaws , let the team know how you go?

**Comment by vhiribarren** [comment]
Hi here, we had the same issue with 1.10.1. Region is eu-west-1. Same error message. We use it with the configuration stored in GitHub.

We did updated LZA to 1.11.2 in a staging environment as suggested above, and I observed the following things:

- indeed, it unblocked our LZA pipeline, as is the installer took the latest token and updated it in LZA
- *however*, when I did try to change the GitHub token again, the UpdatePipelineGithubToken still failed with the same error message (same one than the original poster wrote)

So for us, if upgrading LZA did unblock the pipeline, we fear it will break again at next GitHub token update.

**Comment by vhiribarren** [comment]
> Hi here, we had the same issue with 1.10.1. Region is eu-west-1. Same error message. We use it with the configuration stored in GitHub.
> 
> We did update LZA to 1.11.2 in a staging environment as suggested above, and I observed the following things:
> 
> * indeed, it unblocked our LZA pipeline, as if the installer took the latest token and updated it in LZA
> * **however**, when I did try to change the GitHub token again, the UpdatePipelineGithubToken Lambda still failed with the same error message (same one than the original poster wrote)

A followup from my comment above: with LZA 1.11.2, I recently had to renew the GitHub token, and once again the UpdatePipelineGithubToken Lambda failed, with same error message, so 1.11.2 did not fixed the issue.

Upgrading to 1.12.2 (after having changed the GitHub token) once again did the trick, as if updating LZA is the only possible way to configure a new token.

By the way, since now it is possible to use LZA with configuration stored on GitHub and using AWS CodeConnection, is this GitHub token really needed?

**Comment by mckraken** [comment]
> By the way, since now it is possible to use LZA with configuration stored on GitHub and using AWS CodeConnection, is this GitHub token really needed?

This is our question as well.

**Comment by NickWalt01** [comment]
Hi

The GitHub token expired in our account and didn't want to upgrade to a later version, instead manually invoked the Lambda to get around the problem.

1. Create new inline policy on the Lambda role:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "secretsmanager:*",
            "Resource": "arn:aws:secretsmanager:eu-west-2:<ACCOUNT-NUMBER>:secret:accelerator/github-token-ABCD"
        },
        {
            "Effect": "Allow",
            "Action": "codestar-connections:*",
            "Resource": "arn:aws:codeconnections:us-east-1:<ACCOUNT-NUMBER>:connection/<ID>"
        }
    ]
}
```

2. In the Lambda, go to Code section, Test, and use a CloudWatch event with:

```
{
    "id": "example",
    "detail-type": "Scheduled Event",
    "source": "aws.events",
    "account": "123456789012",
    "time": "1970-01-01T00:00:00Z",
    "region": "us-east-1",
    "resources": [
        "arn:aws:events:us-east-1:123456789012:rule/ExampleRule"
    ],
    "detail": {
        "eventSource": [
            "secretsmanager.amazonaws.com"
        ],
        "requestParameters": {
            "secretId": "arn:aws:secretsmanager:eu-west-2:<ACCOUNT-NUMBER>:secret:accelerator/github-token"
        },
        "eventName": [
            "UpdateSecret",
            "PutSecretValue"
        ]
    }
}
```

3. Run AWSAccelerator-Pipeline in CodePipeline
